### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by VapiSoft** [EdgeVerve/oe-cloud#2]
I tried to install and run it.
On Windows:
$node . 
=>
Connection fails:  { Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:27017' }

In Linux: UBUNTU
$ node .
=>
Throw in: module.js:327
Error: Cannot find module 'strong-remoting'

**Comment by atul-github** [comment]
Hi,
you should have mongodb server running locally (localhost - 127.0.0.1) on 27017 port.
oecloud uses mongodb by default.
if mongodb is running on some other system, please modify server/datasources.json  file and change "**db**" settings accordingly to make this work.

Thanks,
Atul
