### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by givemesumthing** [EdgeVerve/oe-cloud#7]
I have mongo v3.4.7,  node v6.11.2 & npm v3.10.10. While installing i get the  following error : -

`npm WARN deprecated node-uuid@1.4.7: Use uuid module instead`
`npm WARN deprecated nodemailer@1.11.0: All versions below 4.0.1 of Nodemailer ar`
`e deprecated. See https://nodemailer.com/status/`
`npm WARN deprecated gcloud@0.10.0: gcloud has been renamed to google-cloud. To g`
`et new features and bug fixes, you must use the new package.`
`npm WARN deprecated node-uuid@1.4.8: Use uuid module instead`
`npm WARN deprecated mongodb@2.0.55: Please upgrade to 2.2.19 or higher`
`npm WARN deprecated i18next-client@1.10.3: you can use npm install i18next from`
`version 2.0.0`
`npm ERR! Windows_NT 6.3.9600`
`npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\`
`node_modules\\npm\\bin\\npm-cli.js" "install"`
`npm ERR! node v6.11.2`
`npm ERR! npm  v3.10.10`
`npm ERR! code ETARGET`
`npm ERR! notarget No compatible version found: bunyan-prettystream@^3.1.4`
`npm ERR! notarget Valid install targets:`
`npm ERR! notarget 0.1.3, 0.1.2, 0.1.0`
`npm ERR! notarget`
`npm ERR! notarget This is most likely not a problem with npm itself.`
`npm ERR! notarget In most cases you or one of your dependencies are requesting`
`npm ERR! notarget a package version that doesn't exist.`
`npm ERR! notarget`
`npm ERR! notarget It was specified as a dependency of 'oe-logger'`
`npm ERR! notarget`
`npm ERR! Please include the following file with any support request:`
`npm ERR!     D:\InstalledProgrames\oe-cloud\oe-cloud\npm-debug.log`

My understanding is. it's trying to install bunyan-prettystream v3.1.4 which does not exist. or is it something else ? I have also tried explicitly passing the version 0.1.2 in package.json, but it still throws the same error. Can anyone help me identify a fix/workaround ?

**Comment by pktippa** [comment]
@givemesumthing Thanks for reporting the issue, working on it.

**Comment by pktippa** [comment]
@givemesumthing Fixed the installation problems issue, can you please try to do `npm install --no-optional` again.

**Comment by givemesumthing** [comment]
Thanks Issue resolved
