### ISSUE TITLE
Getting generator error on running `oe ui-app` ?

### ISSUE THREAD

**Issue by givemesumthing** [EdgeVerve/oe-cloud#8]
D:\oe-cloud\Apps>oe ui-app
Error ui-app
You don't seem to have a generator with the name "ui-app" installed.
But help is on the way:
You can see available generators via npm search oe-generator or via http://yeoma
n.io/generators/.
Install them with npm install generator-ui-app.
To see all your installed generators run yo without any arguments. Adding the --
help option will also show subgenerators.
If yo cannot find the generator, run yo doctor to troubleshoot your system.

**Comment by givemesumthing** [comment]
Installing generators from npm install generator-ui-app also dosent resolve the error

**Comment by givemesumthing** [comment]
tried installing : 
npm install oe-generator
npm install oe-environment
npm install oe-starter-app
npm install oe-ui-app
npm install generator-oe-h5
npm install generator-oe-base

but the error still persists...

**Comment by pktippa** [comment]
To directly use 
> oe ui-app

need to install [oe-ui-app](https://www.npmjs.com/package/oe-ui-app) package globally.

> npm i -g oe-ui-app

Then you can directly use `oe ui-app` to get started with sample UI app generation.

To follow official guide.
There is a guide for Sample UI App generation from oecloud, please follow this link https://www.oecloud.io/guide/getting-started-with-ui let us know if you still face issues.

**Comment by givemesumthing** [comment]
Have installed oe-ui-app package globally via  `npm i -g oe-ui-app`, but the error still persists

**Comment by shubham201** [comment]
@givemesumthing I just tried, it works fine for me. You might be having some configuration issue or try updating your npm & node or restart your terminal. It might help, not sure though.

**Comment by pktippa** [comment]
@givemesumthing Can you give us more details about your environment, to replicate the issue in ours..

* Operating System details

And Versions of 
* Node
* NPM
* oe-cloud-cli
* oe-ui-app

**Comment by givemesumthing** [comment]
issue resolved
