### ISSUE TITLE
Broken Link on oecloud.io

### ISSUE THREAD

**Issue by luckyabhishek** [EdgeVerve/oe-cloud#9]
There's a blog link on https://www.oecloud.io which points to https://blog.oecloud.io/ and gives 503 Service Unavailable. 
Can you please have a look at that ?

**Comment by soumyadipDe** [comment]
Thanks @luckyabhishek for visiting oecloud.io! :-)
Team is looking into this.

**Comment by raghav135** [comment]
Done now.
